apiVersion: v1
kind: Service
metadata:
  name: tictactoe
  namespace: fx
  labels:
    io.kompose.service: tictactoe
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  selector:
    io.kompose.service: tictactoe
  type: NodePort