apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: fx
  labels:
    io.kompose.service: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/
      restartPolicy: Always
      volumes:
      - name: mongo-persistent-storage
        hostPath:
          path: /data/
          type: Directory