apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: fx
  labels:
    io.kompose.service: mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongo